---
# API DNS primary zone setup
- name: Add {{ dns_zone }}
  uri:
    url: "{{ dns_address }}/api/zones/create"
    body:
      token: "{{ token }}"
      zone: "{{ dns_zone }}"
      type: "Primary" 
      useSoaSerialDateScheme: false
    body_format: form-urlencoded
    method: POST
    status_code: 200

- name: Set Dynamic Updates (RFC 2136) to Allow
  uri:
    url: "{{ dns_address }}/api/zones/options/set"
    body:
      token: "{{ token }}"
      zone: "{{ dns_zone }}"
      overrideCatalogQueryAccess: false
      overrideCatalogZoneTransfer: false
      overrideCatalogNotify: false
      primaryZoneTransferProtocol: "Tcp"
      primaryZoneTransferTsigKeyName: null
      validateZone: false
      queryAccess: "Allow"
      zoneTransfer: "AllowOnlyZoneNameServers"
      zoneTransferNetworkACL: false
      zoneTransferTsigKeyNames: false
      notify: "ZoneNameServers"
      notifyNameServers: false
      notifySecondaryCatalogsNameServers: false
      update: "Allow"
      updateNetworkACL: false
      updateSecurityPolicies: false
    body_format: form-urlencoded
    method: POST
    status_code: 200