[pm]
pm1 ansible_ssh_user=root ansible_host=192.168.0.200
pm2 ansible_ssh_user=root ansible_host=192.168.0.201
pm3 ansible_ssh_user=root ansible_host=192.168.0.202

[dns_primary]
ns1 ansible_ssh_user=ansible ansible_host=192.168.0.210


[dns_secondary]
ns2 ansible_ssh_user=ansible ansible_host=192.168.0.211
; dns3 ansible_ssh_user=ansible ansible_host=192.168.0.245

[reverse_proxy_primary]
reverseProxy1 ansible_ssh_user=ansible ansible_host=192.168.0.215

; [jellyfin]
; jellyfin1 ansible_ssh_user=ansible ansible_host=192.168.0.230